all tests pass again

diff --git a/scripts/sync-repos b/scripts/sync-repos
--- a/scripts/sync-repos
+++ b/scripts/sync-repos
@@ -1,7 +1,6 @@
 #!/bin/bash
 set -e
 source /etc/environment
-#TODO add quarantine dir and check PGP keys
 
 script_repo=${SCRIPT_REPO?}
 script_dir=/home/user/repos/scripts
@@ -11,6 +10,8 @@ key_repo=${KEY_REPO?}
 key_dir=/home/user/repos/keys
 temp_key_dir=$(mktemp -d -p /dev/shm)
 key_repo_host=$(echo "${KEY_REPO}" | sed 's/.*@\([a-z0-9-]\+\).*/\1/g')
+
+gpg --import /etc/keys/pgp/*.pub
 
 echo "$USER"
 mkdir -p ~/.ssh
@@ -23,11 +24,14 @@ signer=$(
 	git \
 		-C "$temp_script_dir" \
 		verify-commit --raw HEAD 2>&1 \
-	| grep GOODSIG \
-	| awk '{ print $3 }' \
+	| grep VALIDSIG \
+	| awk '{ print $12 }' \
 )
+[[ "$signer" ]] || (>&2 echo "Error: Unknown signer on scripts repo"; exit 1)
+echo "Signer is $signer"
 [[ "$ADMIN_FINGERPRINTS" =~ $signer ]] || \
-	{ echo "Head must be signed by admin"; exit 1; }
+	(>&2 echo "Error: Head must be signed by admin"; exit 1 )
+mkdir -p "$script_dir"
 cp -R "$temp_script_dir"/* "$script_dir"/
 
 git clone "$key_repo" "$temp_key_dir"
@@ -37,11 +41,12 @@ signer=$(
 	git \
 		-C "$temp_key_dir" \
 		verify-commit --raw HEAD 2>&1 \
-	| grep GOODSIG \
-	| awk '{ print $3 }' \
+	| grep VALIDSIG \
+	| awk '{ print $12 }' \
 )
+[[ "$signer" ]] || (>&2 echo "Error: Unknown signer on keys repo"; exit 1)
+echo "Signer is $signer"
 [[ "$ADMIN_FINGERPRINTS" =~ $signer ]] || \
-	{ echo "Head must be signed by admin"; exit 1; }
+	(>&2 echo "Head must be signed by admin"; exit 1 )
+mkdir -p "$key_dir"
 cp -R "$temp_key_dir"/* "$key_dir"/
-
-
